### PR TITLE
Add automations run updated event trigger support

### PR DESCRIPTION
**Pull request by pazhersh**
# Description

What - Add support for the upcoming "run updated" automation event type
How - Added the relevant models and schemas to support creating such an action

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

### CODE REVIEW

**Review by erikzaadi — COMMENTED** [review]
Looks great, add examples + docs as well?

**Comment by pazhersh** [comment]
I don't think this requires specific examples / docs
The way you use it is the same as any other automation event type

**Comment by pazhersh** [comment]
The docs that are auto-generated should be enough
but I did add examples ✨

**Review by erikzaadi — APPROVED** [review]

**Pull request merged**
